In [1]:
import numpy as np

## 1.2.1 Linear spaces

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

#Vector addition
v_addition = v1 + v2

#Scalar multiplication
scalar = 10
v_scalar = v1 * scalar

print("Vector v1:", v1)
print("Vector v2:", v2)
print("Vector addition:", v_addition)
print("Scalar multiplication:", v_scalar)

Vector v1: [1 2 3]
Vector v2: [4 5 6]
Vector addition: [5 7 9]
Scalar multiplication: [10 20 30]


## 1.2.2 Orthogonality

In [10]:
v = np.array([0, 1, 0])
u = np.array([1, 0, 0])

#dot product
dot_prdct = np.dot(u, v)

print("Vector u:", u)
print("Vector v:", v)
print("Dot product:", dot_prdct)

if dot_prdct == 0:
    print("Vectors u and v are orthogonal.")
else:
    print("Vectors u and v aren't orthogonal.")


Vector u: [1 0 0]
Vector v: [0 1 0]
Dot product: 0
Vectors u and v are orthogonal.


## 1.2.3 Gram-Schmidt process

In [16]:
v1 = np.array([1.0, 0.0])
v2 = np.array([1.0, 1.0])
vectors = np.array([v1, v2])

ortho_vectors = []

# Gram-Schmidt 
for v in vectors:
    w = v.copy()
    for u in ortho_vectors:
        w -= np.dot(u, v) / np.dot(u, u) * u
    ortho_vectors.append(w)

ortho_vectors = np.array(ortho_vectors)

print("Orthogonal vectors:")
print(ortho_vectors)

ortho_vectors_norm = np.array([v / np.linalg.norm(v) for v in ortho_vectors])

print("Orthonormal vectors after Gram-Schmidt process:")
print(ortho_vectors_norm)


Orthogonal vectors:
[[1. 0.]
 [0. 1.]]
Orthonormal vectors after Gram-Schmidt process:
[[1. 0.]
 [0. 1.]]


## 1.2.4 Eigenvalues and eigenvectors

In [19]:
m1 = np.array([[1,2],
               [1,2]])

eigenvalues, eigenvectors = np.linalg.eig(m1)
print("Matrix A:")
print(m1)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)

Matrix A:
[[1 2]
 [1 2]]
Eigenvalues of A: [0. 3.]
Eigenvectors of A:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]
