In [17]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


# Singular Value Decomposition

In [18]:
def svd(A):
    ATA = np.dot(A.T, A)
    eigen_v, v = np.linalg.eig(ATA)
    sort = np.argsort(eigen_v)[: : -1]
    eigen_v = eigen_v[sort]
    v = v[:, sort]
    sing_val = np.sqrt(eigen_v)
    u = np.dot(A, v)
    u = u / sing_val
    sigma = np.zeros_like(A, dtype=float)
    np.fill_diagonal(sigma, sing_val)
    
    return u, sigma, v.T

u, sigma, vT = svd(A)
print("U: \n", u)
print("Sigma:\n", sigma)
print("V^T:\n", vT)

U: 
 [[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]
Sigma:
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
V^T:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Low-rank Matrix Approximations

In [19]:
def lr_a(A, k):
    u, sigma, vT = svd(A)
    u_k = u[:, :k]
    sigma_k = sigma[:k, :k]
    vT_k = vT[:k, :]

    A_k = np.dot(u_k, np.dot(sigma_k, vT_k))

    return A_k

A_k = lr_a(A, k=1)
print("Low-rank approximation:\n", A_k)

Low-rank approximation:
 [[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


# Principal Component Analysis

In [20]:
def pca(A, n_comp):
    A_cent = A - np.mean(A, axis=0)
    cov_mat = np.dot(A_cent.T, A_cent) / (A_cent.shape[0] - 1)
    u, sigma, vT = svd(cov_mat)
    W = vT.T[:, :n_comp]
    A_pca = np.dot(A_cent, W)

    return A_pca

A_pca = pca(A, n_comp=1)
print("PCA Result:\n", A_pca)

PCA Result:
 [[-2.82842712]
 [ 0.        ]
 [ 2.82842712]]
